import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postgres from "postgres";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
export const projectRoot = path.resolve(__dirname, "..");

const defaultServices = [
  {
    name: "Haircut",
    description: "Classic precision haircut tailored to your style.",
    duration_minutes: 45,
    price: 30,
    category: "Hair",
  },
  {
    name: "Hair Color",
    description: "Full-service professional coloring treatment.",
    duration_minutes: 120,
    price: 80,
    category: "Hair",
  },
  {
    name: "Blowout",
    description: "Shampoo and sleek blow-dry finishing service.",
    duration_minutes: 60,
    price: 45,
    category: "Hair",
  },
  {
    name: "Facial",
    description: "Deep cleansing and hydrating facial treatment.",
    duration_minutes: 75,
    price: 65,
    category: "Skincare",
  },
  {
    name: "Manicure",
    description: "Nail shaping, cuticle care, and polish application.",
    duration_minutes: 45,
    price: 25,
    category: "Nails",
  },
  {
    name: "Pedicure",
    description: "Foot soak, exfoliation, and polish service.",
    duration_minutes: 60,
    price: 35,
    category: "Nails",
  },
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return;
  }

  const content = fs.readFileSync(filePath, "utf8");
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const separatorIndex = line.indexOf("=");
    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, "");

    if (key && process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

export function loadProjectEnv() {
  parseEnvFile(path.join(projectRoot, ".env"));
  parseEnvFile(path.join(projectRoot, ".env.local"));
}

export function getConnectionString() {
  return (
    process.env.DATABASE_URL ||
    process.env.POSTGRES_URL ||
    process.env.POSTGRES_PRISMA_URL ||
    ""
  );
}

export function getSqlClient() {
  const connectionString = getConnectionString();
  if (!connectionString) {
    throw new Error("DATABASE_URL or POSTGRES_URL is required.");
  }

  return postgres(connectionString, {
    max: 1,
    prepare: false,
  });
}

export async function ensureSchema(sql) {
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      name TEXT,
      email TEXT UNIQUE,
      password TEXT,
      role TEXT DEFAULT 'user',
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS services (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      description TEXT,
      duration_minutes INTEGER,
      price NUMERIC(10, 2),
      category TEXT
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS bookings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone_number TEXT,
      customer_name TEXT,
      user_id TEXT,
      service_name TEXT,
      appointment_date TEXT,
      appointment_time TEXT,
      status TEXT DEFAULT 'confirmed',
      notes TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone_number TEXT,
      customer_name TEXT,
      content TEXT,
      is_read BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS conversations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone_number TEXT,
      role TEXT,
      content TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS whatsapp_users (
      phone_number TEXT PRIMARY KEY,
      name TEXT,
      last_seen TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  const [{ count }] = await sql`
    SELECT COUNT(*)::int AS count
    FROM services
  `;

  if (count === 0) {
    for (const service of defaultServices) {
      await sql`
        INSERT INTO services (name, description, duration_minutes, price, category)
        VALUES (${service.name}, ${service.description}, ${service.duration_minutes}, ${service.price}, ${service.category})
        ON CONFLICT (name) DO NOTHING
      `;
    }
  }
}

export async function getTableCounts(sql) {
  const tableNames = ["users", "services", "bookings", "messages", "conversations", "whatsapp_users"];
  const counts = {};

  for (const tableName of tableNames) {
    const [row] = await sql.unsafe(`SELECT COUNT(*)::int AS count FROM ${tableName}`);
    counts[tableName] = row.count;
  }

  return counts;
}
